### ISSUE TITLE
Fix Slack request verification

### ISSUE THREAD

**Issue by gfting** [VandyHacks/nimbus#1]
# Description
We'd like to verify that requests come from Slack to ensure random requests are not fielded.

# Relevant files
- A current attempt is in [./src/utils/index.ts](./src/utils/index.ts) using the Worker runtime [SubtleCrypto](https://developers.cloudflare.com/workers/runtime-apis/web-crypto) library. `digest()` doesn't work because it doesn't use the key to hash.
- Another approach could use an npm library to handle the hashes rather than doing something manually. Note that for newcomers to TypeScript, a types library may also need to be imported.

**Comment by aadibajpai** [comment]
https://api.slack.com/authentication/verifying-requests-from-slack
