### ISSUE TITLE
Support vhl.ink methods

### ISSUE THREAD

**Issue by gfting** [VandyHacks/nimbus#2]
# Description
Currently, this only handles POST requests to make a new shortened link. Other methods such as getting the list of links and deleting are not yet supported.

# Relevant Information
[./src/handlers/shorten.ts] has the POST, other handlers can be added here to support command options, or entirely new slash commands could be added. A button or small interface would also be an interesting option.

**Comment by aadibajpai** [comment]
I think `/shorten list` to see all the current short links would be good. Can be just made to execute and filter the output from current LIST method to get a list of current short links.
