### ISSUE TITLE
Add firehose for logging

### ISSUE THREAD

**Issue by aadibajpai** [VandyHacks/nimbus#7]
Given multiple users of the slash command, it would be useful to have logging to a channel for both audit and potential bug fixing purposes. 

This can likely be done by just making a function that sends a message to the #bot-status channel in slack every time there's a URL shortened or deleted. Something like `@xyz shortened https://vhl.ink/abc to https://whatever.com`. Preferably without pinging the person if there is a way. Similarly for deletes.

Now this would not log any action that happens in vhl.ink directly and not through nimbus but that is okay imo, since even if we log in vhl.ink we wouldn't know who did it.

**Comment by Ace314159** [comment]
Firehose for deleting has not been implemented since the #6 hasn't been merged in yet.

**Comment by Ace314159** [comment]
Implemented by #10
